# Seed users - development profile only
seed.admin.username=${SEED_ADMIN_USERNAME}
seed.admin.password=${SEED_ADMIN_PASSWORD}

seed.user.username=${SEED_USER_USERNAME}
seed.user.password=${SEED_USER_PASSWORD}